# ProGuard rules for the installer app.

# Keep the entry-point Activity
-keep class cafe.bluearchive.installer.InstallerActivity { *; }
-keep class cafe.bluearchive.installer.InstallerActivity$UiState { *; }

# Keep BuildConfig fields (generated by AGP)
-keep class cafe.bluearchive.installer.BuildConfig { *; }

# Shizuku API
-keep class rikka.shizuku.** { *; }
-keep class moe.shizuku.** { *; }

# Shizuku UserService — keep constructors that Shizuku reflects into
-keep class cafe.bluearchive.installer.ShizukuShellService { *; }
-keepclassmembers class cafe.bluearchive.installer.ShizukuShellService {
    public <init>(...);
}

# Shizuku AIDL stubs (used across process boundaries via Binder)
-keep class cafe.bluearchive.installer.shizuku.IShellService { *; }
-keep class cafe.bluearchive.installer.shizuku.IShellService$Stub { *; }
-keep class cafe.bluearchive.installer.shizuku.ShellResult { *; }
-keepclassmembers class cafe.bluearchive.installer.shizuku.ShellResult$Creator { *; }

# libsu
-keep class com.topjohnwu.superuser.** { *; }
