# ProGuard rules for the installer app.

# Keep the entry-point Activity
-keep class cafe.bluearchive.installer.InstallerActivity { *; }
-keep class cafe.bluearchive.installer.InstallerActivity$UiState { *; }

# Keep BuildConfig fields (generated by AGP)
-keep class cafe.bluearchive.installer.BuildConfig { *; }
